var ipsum = 
	[
		"A modern-day warrior, mean mean stride, today's Tom Sawyer, mean mean pride.",
		"Though his mind is not for rent, don't put him down as arrogant.", 
		"His reserve, a quiet defense, riding out the day's events - the river.",
		"What you say about his company is what you say about society.",
		"Catch the mist - Catch the myth - Catch the mystery - Catch the drift.",
		"The world is. The world is. Love and life are deep. Maybe as his skies are wide.",
		"Today's Tom Sawyer, he gets high on you, and the space he invades he gets by on you.",
		"No, his mind is not for rent to any god or government.",
		"Always hopeful, yet discontent, he knows changes aren't permanent - but change is.",
		"Catch the witness - Catch the wit - Catch the spirit - Catch the spit.",
	 	"Exit the warrior, today's Tom Sawyer, he gets high on you and the energy you trade.",
	   	"He gets right on to the friction of the day.",
	   	"My uncle has a country place, that no-one knows about.",
	   	"He says it used to be a farm, before the Motor Law.", 
		"Sundays I elude the 'Eyes', and hop the Turbine Freight to far outside the Wire, where my white-haired uncle waits.",
		"Jump to the ground as the Turbo slows to cross the borderline.", 
		"Run like the wind as excitement shivers up and down my spine.", 
		"Down in his barn, my uncle preserved for me an old machine - for fifty-odd years.", 
		"To keep it as new has been his dearest dream.",
		"I strip away the old debris, that hides a shining car, a brilliant red Barchetta from a better, vanished time.", 
		"Fire up the willing engine, responding with a roar!", 
		"Tires spitting gravel, I commit my weekly crime...", 
		"Wind in my hair - shifting and drifting - mechanical music - adrenalin surge.", 
		"Well-weathered leather, hot metal and oil, the scented country air.",
		"Sunlight on chrome, the blur of the landscape, every nerve aware.",
		"Suddenly ahead of me, across the mountainside, a gleaming alloy air-car shoots towards me, two lanes wide.",
		"I spin around with shrieking tires, to run the deadly race.",
		"Go screaming through the valley as another joins the chase.",
		"Drive like the wind , straining the limits of machine and man.", 
		"Laughing out loud with fear and hope, I've got a desperate plan.", 
		"At the one-lane bridge, I leave the giants stranded at the riverside.", 
		"Race back to the farm to dream with my uncle at the fireside...",
		"Living on a lighted stage approaches the unreal for those who think and feel in touch with some reality beyond the gilded cage.", 
		"Cast in this unlikely role, ill-equipped to act with insufficient tact, one must put up barriers to keep oneself intact.",
		"Living in the Limelight the universal dream for those who wish to seem.", 
		"Those who wish to be must put aside the alienation get on with the fascination, the real relation, the underlying theme.",
		"Living in a fisheye lens caught in the camera eye, I have no heart to lie.", 
		"I can't pretend a stranger is a long-awaited friend.",
		"All the world's indeed a stage, and we are merely players, performers and portrayers, each another's audience outside the gilded cage.",
		"There is unrest in the Forest.", 
		"There is trouble with the trees, for the Maples want more sunlight and the Oaks ignore their pleas.",
		"The trouble with the Maples (and they're quite convinced they're right), they say the Oaks are just too lofty and they grab up all the light.",
		"But the Oaks can't help their feelings, if they like the way they're made, and they wonder why the Maples can't be happy in their shade?",
		"There is trouble in the Forest, and the creatures all have fled, as the Maples scream 'Oppression!' and the Oaks, just shake their heads.", 
		"So the Maples formed a Union and demanded equal rights, 'The Oaks are just too greedy. We will make them give us light.'", 
		"Now there's no more Oak oppression for they passed a noble law, and the trees are all kept equal by hatchet, axe, and saw...",
		"And the meek shall inherit the earth.",
		"The massive grey walls of the Temples rise from the Heart of every Federation city.",
		"I have always been awed by them, to think that every single facet of every life is regulated and directed from within!",
		"Our books, our music, our work and play are all looked after by the benevolent wisdom of the priests...",
		"We've taken care of everything, the words you read, the songs you sing, the pictures that give pleasure to your eye.", 
		"One for all and all for one. Work together common sons.",
		"Never need to wonder how or why.",
		"We are the Priests of the Temples of Syrinx.",
		"Our great computers fill the hallowed halls.",
		"All the gifts of life are held within our walls.",
		"Look around this world we made, equality, our stock in trade.",
		"Come and join the Brotherhood of Man, what a nice contented world.", 
		"Let the banners be unfurled. Hold the Red Star proudly high in hand.",
		"Behind my beloved waterfall, in the little room that was hidden beneath the cave, I found it.",
		"I brushed away the dust of the years, and picked it up, holding it reverently in my hands.",
		"I had no idea what it might be, but it was beautiful.",
		"I learned to lay my fingers across the wires, and to turn the keys to make them sound differently.",
		"As I struck the wires with my other hand, I produced my first harmonious sounds, and soon my own music!",
		"How different it could be from the music of the Temples! I can't wait to tell the priests about it! ...",
		"What can this strange device be?",
		"When I touch it, it gives forth a sound.",
		"It's got wires that vibrate, and give music.",
		"What can this thing be that I found?",
		"See how it sings like a sad heart and joyously screams out its pain.",
		"Sounds that build high like a mountain or notes that fall gently, like rain.",
		"I can't wait to share this new wonder.",
		"The people will all see its light.",
		"Let them all make their own music.",
		"The Priests praise my name on this night.",
		"In the sudden silence as I finished playing, I looked up to a circle of grim, expressionless faces.",
		"Father Brown rose to his feet, and his somnolent voice echoed throughout the silent Temple Hall.",
		"Instead of the grateful joy that I expected, they were words of quiet rejection!", 
		"Instead of praise, sullen dismissal.",
		"I watched in shock and horror as Father Brown ground my precious instrument to splinters beneath his feet...",
		"I know it's most unusual to come before you so, but I've found an ancient miracle. I thought that you should know.", 
		"Listen to my music and hear what it can do.",
		"There's something here as strong as life. I know that it will reach you.",
		"Yes, we know. It's nothing new. It's just a waste of time.",
		"We have no need for ancient ways.",
		"Our world is doing fine.",
		"Another toy that helped destroy the elder race of man.",
		"Forget about your silly whim. It doesn't fit the plan.",
		"I can't believe you're saying.",
		"These things just can't be true.",
		"Our world could use this beauty.",
		"Just think what we might do.",
		"Don't annoy us further; we have our work to do.",
		"Just think about the average. What use have they for you?",
		"I guess it was a dream, but even now it all seems so vivid to me.",
		"Clearly yet I see the beckoning hand of the oracle as he stood at the summit of the staircase.",
		"I see still the incredible beauty of the sculptured cities, and the pure spirit of man revealed in the lives and works of this world.",
		"I was overwhelmed by both wonder and understanding as I saw a completely different way to life, a way that had been crushed by the Federation long ago.",
		"I saw now how meaningless life had become with the loss of all these things...",
		"I wandered home though the silent streets and fell into a fitful sleep.",
		"Escape to realms beyond the night, dream - can't you show me the light?",
		"I stand atop a spiral stair.", 
		"An oracle confronts me there.",
		"He leads me on, light years away  through astral nights, galactic days.",
		"I see the works of gifted hands grace this strange and wondrous land.",
		"I see the hand of man arise with hungry mind and open eyes.",
		"They left the planet long ago.",
		"The elder race still learn and grow.",
		"Their power grows with purpose strong to claim the home where they belong.",
		"Home to tear the Temples down. Home to change.",
		"I have not left this cave for days now.",
		"It has become my last refuge in my total despair.",
		"I have only the music of the waterfall to comfort me now.",
		"I can no longer live under the control of the Federation, but there is no other place to go.",
		"My last hope is that with my death I may pass into the world of my dream, and know peace at last.",
		"The sleep is still in my eyes.",
		"The dream is still in my head.",
		"I heave a sigh, and sadly smile. And lie a while in bed.",
		"I wish that it might come to pass, not fade like all my dreams.",
		"Just think of what my life might be in a world like I have seen.",
		"I don't think I can carry on this cold and empty life.",
		"My spirits are low. In the depths of despair, my lifeblood spills over...",
		"Attention all Planets of the Solar Federation, we have assumed control.",
		"I had heard the whispered tales of immortality, the deepest mystery from an ancient book.",
		"I scaled the frozen mountain tops of eastern lands unknown.",
		"Time and Man alone searching for the lost - Xanadu - to stand within The Pleasure Dome.",
		"Decreed by Kubla Khan to taste anew the fruits of life.",
		"The last immortal man.",
		"To find the sacred river Alph, to walk the caves of ice.",
		"Oh, I will dine on honey dew and drink the milk of Paradise.",
		"A thousand years have come and gone but time has passed me by.",
		"Stars stopped in the sky, frozen in an everlasting view, waiting for the world to end.",
		"Weary of the night, praying for the light, prison of the lost - Xanadu",
	 	"Held within The Pleasure Dome, decreed by Kubla Khan, to taste my bitter triumph.", 
		"As a mad immortal man, nevermore shall I return, escape these caves of ice, for I have dined on honey dew and drunk the milk of Paradise.",
		"Sprawling on the fringes of the city in geometric order.",
		"An insulated border in between the bright lights and the far unlit unknown.",
		"Growing up it all seems so one-sided, opinions all provided, the future pre-decided, detached and subdivided in the mass production zone.",
		"Nowhere is the dreamer or the misfit so alone.",
		"Subdivisions - in the high school halls, in the shopping malls, conform or be cast out.",
		"Subdivisions - in the basement bars, in the backs of cars, be cool or be cast out.",
		"Any escape might help to smooth the unattractive truth, but the suburbs have no charms to soothe the restless dreams of youth.",
		"Drawn like moths we drift into the city the timeless old attraction.",
		"Cruising for the action lit up like a firefly just to feel the living night.",
		"Some will sell their dreams for small desires or lose the race to rats.",
		"Get caught in ticking traps and start to dream of somewhere to relax their restless flight.",
		"Somewhere out of a memory of lighted streets on quiet nights... ",
		"Begin the day with a friendly voice.",
		"Companion, unobtrusive, plays the song that's so elusive, and the magic music makes your morning mood.",
		"Off on your way, hit the open road.",
		"There is magic at your fingers for the Spirit ever lingers dndemanding contact on your happy solitude.",
		"Invisible airwaves crackle with life.",
		"Bright antennae bristle with the energy.",
		"Emotional feedback on a timeless wavelength, bearing a gift beyond price.",
		"Almost free... all this machinery, making modern music.",
		"Can still be open-hearted, not so coldly charted.",
		"It's really just a question of your honesty.",
		"One likes to believe in the freedom of music, but glittering prizes and endless compromises shatter the illusion of integrity.",
		"For the words of the profits are written on the studio wall.",
		"Concert hall echoes with the sounds of salesmen."
	]

